name: Test Build & Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ deploy ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Enable Yarn
        run: corepack enable
      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
      - name: Install dependencies
        run: yarn install
      - name: Build (yarn)
        env:
          CI: ${{ vars.CI || 'false' }}
          REACT_APP_BASE_API_URL: ${{ vars.BASE_API_URL }}
        run: yarn build
      - name: Run tests if test files exist
        run: |
          if ls src/**/*.{spec,test}.{js,jsx,ts,tsx} 1> /dev/null 2>&1; then
            yarn test --watchAll=false
          else
            echo "No test files found, skipping tests."
          fi